### ISSUE TITLE
The lack of libiPhone_ean. So

### ISSUE THREAD

**Issue by fuliteng** [ApolloAuto/apollo-DuerOS#1]
nativeLibraryDirectories=[/data/app/com.baidu.carlifevehicle-2/lib/arm, /vendor/lib, /system/lib]]] couldn't find "libiPhone_ean.so"
                                                                            at java.lang.Runtime.loadLibrary(Runtime.java:367)
                                                                            at java.lang.System.loadLibrary(System.java:1076)
                                                                            at com.baidu.carlifevehicle.connect.JniEanMethod.<clinit>(JniEanMethod.java:20)
                                                                            at com.baidu.carlifevehicle.connect.JniEanMethod.openEan(Native Method)
                                                                            at com.baidu.carlifevehicle.connect.EanConnectManager.eanInit(EanConnectManager.java:81)
                                                                            at com.baidu.carlifevehicle.connect.EanConnectManager$EanConnectThread.run(EanConnectManager.java:210)

**Comment by lebang08** [comment]
邮箱给我个，libiPhone_ean.so库我发你

**Comment by fuliteng** [comment]
邮箱:1693238185@qq.com 
/data/local/tmp/ncm.sock 这个文件是运行生成的吗 ？

------------------------------------------------------------------发件人：LeBang <notifications@github.com>发送时间：2018年1月15日(星期一) 18:14收件人：ApolloAuto/apollo-DuerOS <apollo-DuerOS@noreply.github.com>抄　送：fuliteng <fuliteng@aliyun.com>; Author <author@noreply.github.com>主　题：Re: [ApolloAuto/apollo-DuerOS] The lack of libiPhone_ean. So (#1)
邮箱给我个，libiPhone_ean.so库我发你

**Comment by fuliteng** [comment]
@lebang08  邮箱:1693238185@qq.com 
/data/local/tmp/ncm.sock 这个文件是运行生成的吗 ？
因为，ConnectNcmDriverClient.java 内部类 NcmDriverClientThread  
代码 ：ncmLocalSocket.connect(new LocalSocketAddress(socketName)); 直接异常了

**Comment by fuliteng** [comment]
@lebang08  
![image](https://user-images.githubusercontent.com/17795829/34968276-5b5c5782-faa3-11e7-90c7-8304ce7bffbe.png)
这种错误，这个项目 你那有碰到吗

**Comment by lebang08** [comment]
暂时没有碰到 @fuliteng

**Comment by fuliteng** [comment]
@lebang08   
你有这个文件 /data/local/tmp/ncm.sock 吗

**Comment by lebang08** [comment]
没有。其实项目中很多文件我也缺少，比如兼容5.0以下所需的不同版本bdsc文件，希望能够提供
@xczhanjun @luoxubin @startcode @westeast

**Comment by fuliteng** [comment]
@lebang08  我是下载Andorid 手机版本和WinCE版本下来解压，从里面找的

**Comment by xiachunle** [comment]
![image](https://user-images.githubusercontent.com/11811777/35024212-31c2de4c-fb79-11e7-81f5-f86618b68665.png)
同步代码后，传入bdcf文件启动失败了

**Comment by fuliteng** [comment]
@xiachunle  看错误日志，把带有MFI认证相关的代码注释掉先

**Comment by fengcunhan** [comment]
@lebang08 libiPhone_ean.so库文件麻烦发我一个，邮箱是：fengcunhan@126.com

**Comment by the-alone-maple** [comment]
@lebang08 libiPhone_ean.so库文件麻烦发我一个吧，程序一直Crash，邮箱是：2395948007@qq.com,不胜感激！

**Comment by fuliteng** [comment]
@the-alone-maple libiPhone_ean.so有了没，还需要发你不

**Comment by the-alone-maple** [comment]
@fuliteng  还没，麻烦发一个so文件给我吧，非常感谢！

**Comment by the-alone-maple** [comment]
@lebang08 Hi ,请问有libiPhone_ean.so文件否？麻烦发一个so文件给我吧，非常感谢！邮箱：2395948007@.qq.com

**Comment by fukehan** [comment]
> 邮箱给我个，libiPhone_ean.so库我发你

我的邮箱是loushuai@droi.com，请发一个libiPhone_ean.so库给我，谢谢！

**Comment by atan1hao** [comment]
> 邮箱给我个，libiPhone_ean.so库我发你
好心大神，如果有libiPhone_ean.so这个文件的话，麻烦发到我的邮箱：atan1hao@163.com，不胜感激！

**Comment by feixhan** [comment]
不同平台，编译出来的so是不能混用的，要看你什么cpu了。

**Comment by gs666** [comment]
> @the-alone-maple libiPhone_ean.so有了没，还需要发你不

能否发我一个？邮箱gaoshuo521@foxmail.com

**Comment by gs666** [comment]
> 邮箱给我个，libiPhone_ean.so库我发你

gaoshuo521@foxmail.com
感谢

**Comment by gs666** [comment]
> @xiachunle 看错误日志，把带有MFI认证相关的代码注释掉先

gaoshuo521@foxmail.com
感谢

**Comment by JerenQD** [comment]
> 邮箱给我个，libiPhone_ean.so库我发你
帮忙发我一份吧，谢谢 673802662@qq.com

**Comment by JerenQD** [comment]
这个有实现吗？主要实现什么功能？谢谢

**Comment by Kaiwei1981** [comment]
@fuliteng libiPhone_ean.so库能否给我一份，感谢！123447842@qq.com

**Comment by hwmxrhx** [comment]
@fuliteng libiPhone_ean.so库能否给我一份，感谢！417605977@qq.com

**Comment by Qian9** [comment]
@lebang08 @fuliteng @hwmxrhx 各位老板，遇到同样问题，求libiPhone_ean.so，辛苦发一份 

邮箱: witkey_pma@yeah.net

**Comment by JerenQD** [comment]
能帮忙发一份吗？谢谢。673802662@qq.com

**Comment by wutingtingdolla** [comment]
@lebang08 libiPhone_ean.so库文件麻烦发我一个吧，程序一直Crash，邮箱是：190683808@qq.com,不胜感激！
