### ISSUE TITLE
carlife 声音通道没有收到数据 /carlife media ch no data 

### ISSUE THREAD

**Issue by Shuoshukg** [ApolloAuto/apollo-DuerOS#15]
在Ubuntu14中，运行CarLifeLibTest，链接方式是ADB。video通道可以收到H264视频的数据，但是media通道收不到PCM音乐数据，不过可以收到进度条数据。
1.carlife是否需要BT和adb同时链接？然后media数据走蓝牙？
2.在“CarLifeVehicleLib动态链接库使用说明.docx”中有3种建立连接的方式，是因为ubuntu系统中，不能通过ADB连接CarLife吗？

    1) int connectionSetup(string mdIP, string interfaceName)（适用于Linux）
    2) int connectionSetup(string mdIP)（适用于QNX）
    3) int connectionSetup()（适用于ADB）

谢谢，求帮忙解答。

////////////////

In Ubuntu 14, run CarLifeLibTest and the link is ADB. The video channel can receive H264 video data, but the media channel does not receive PCM music data, but can receive progress bar data.
1. Does Carlife need BT and adb to link at the same time?And Is the media data received via the Bluetooth? 
2. There are three ways to establish a connection in the "CarLifeVehicleLib动态链接库使用说明.docx".  Is it because the ubuntu system cannot connect to CarLife through ADB?

     1) int connectionSetup(string mdIP, string interfaceName) (for Linux)
     2) int connectionSetup(string mdIP) (for QNX)
     3) int connectionSetup() (for ADB)

Thanks, please help me.

**Comment by feixhan** [comment]
>1.carlife是否需要BT和adb同时链接？然后media数据走蓝牙？
CarLife 的 正常音乐是走USB通道的，只有 电话 的声音需要走BT。不连BT也是没问题的。

>2.在“CarLifeVehicleLib动态链接库使用说明.docx”中有3种建立连接的方式，是因为ubuntu系统中，不能通过ADB连接CarLife吗？
可以通过ADB连接，ubuntu就先第一种。
1) int connectionSetup(string mdIP, string interfaceName)（适用于Linux）

**Comment by Shuoshukg** [comment]
感谢feixhan的回答。
声音通道没有收到数据的问题解决。
方法：
通过MSG_CMD_HU_FEATURE_CONFIG_RESPONSE
把键：FOCUS_UI，设置ENABLE就可以了，
但是这项代表啥还不是很清楚。
