### ISSUE TITLE
求助！AOA bulktransfer失败

### ISSUE THREAD

**Issue by tulunlxj2017** [ApolloAuto/apollo-DuerOS#22]
车机版安装后连接装有Carlife的Android手机时，一直卡在80%，
log反复打： bulkTransferIn error 1: ret = -1
通过打log，我发现UsbDevice, UsbDeviceConnection, UsbEndpoint等相关的对象都是正常的
buffer和timeout也没有问题
我猜是不是我手机上的Carlife没有采用对应的对接方式？
有人知道怎么回事吗？
或者能否提供一下连接成功的安卓手机端版本号？

**Comment by tulunlxj2017** [comment]
理论上timeout给0的话，即使没有传输对象，bulkTransfer也是阻塞的，而我的情况却是直接返回-1
有没有人遇到过这种情况？

**Comment by xuwenping** [comment]
hi，遇到一样的问题，请问你解决了吗？

**Comment by tulunlxj2017** [comment]
我的情况：
android 会报一个 network in mainthred的异常（具体名字忘了），源码有一部分在ui线程使用了网络操作，找到对应点另开线程处理就好了


 
---原始邮件---
发件人: "xuwenping"<notifications@github.com&gt;
发送时间: 2019年11月26日(星期二) 下午4:46
收件人: "ApolloAuto/apollo-DuerOS"<apollo-DuerOS@noreply.github.com&gt;;
抄送: "State change"<state_change@noreply.github.com&gt;;"tulunlxj2017"<1273061253@qq.com&gt;;
主题: Re: [ApolloAuto/apollo-DuerOS] 求助！AOA bulktransfer失败 (#22)



hi，遇到一样的问题，请问你解决了吗？

**Comment by xuwenping** [comment]
感谢，我试一下
