### ISSUE TITLE
AOA连接方式问题

### ISSUE THREAD

**Issue by lebang08** [ApolloAuto/apollo-DuerOS#3]
AOA链接功能似乎并没有实现。请问AOA方式如何正确使用USB相关的Intent-filter，目前参照谷歌官方例子，将过滤器放在Activity中，实现的效果不是预期的（在Carlife应用没启动时，链接USB线，就会调起应用并去链接）。

而apollo-DuerOS源码，是在广播中加USB相关的Intent-filter，同样会在应用未启动时就调起应用，且并不能正常与手机端进行AOA链接（提示授权，并连续崩溃）。

请问如何实现以下期望功能：
在Carlife应用启动后，链接USB线，才会与手机端匹配。

**Comment by fuliteng** [comment]
苹果手机你是怎么解决的，我安卓手机是可以连接的。

**Comment by lebang08** [comment]
@fuliteng 请教，安卓AOA你没有出现如下问题吗？

现象：连接过程反复弹出权限申请，即使勾选记忆并“确定”，仍会继续弹出（如图1）
![0](https://user-images.githubusercontent.com/16592729/34970735-0bfa7fee-fab1-11e7-9712-86f209cc5321.jpg)

反复确定弹框后，最终连接进度100% ，但立刻显示错误提示（如图2）
![1](https://user-images.githubusercontent.com/16592729/34970829-91c0a680-fab1-11e7-91d3-da59594ac8fd.jpg)

相关日志（如图3）
![2](https://user-images.githubusercontent.com/16592729/34970879-ea35fcde-fab1-11e7-99f4-f32bb15d1e79.png)

日志有所过滤，反馈的事实是AOA连接其实正常在进行，但是可能受权限干扰了（系统不记忆该权限）
另手机端Carlife版本和USB线都没问题，此前自己写的项目一直连接正常。


请问你是做了什么改动规避了这个问题吗？还是直接运行代码并未出现过我这个问题。

**Comment by fuliteng** [comment]
@lebang08 我也是反复弹窗，但最好连上了，期间我换过一台手机，因为手机不支持（没权限进行USB通信）

**Comment by fuliteng** [comment]
@lebang08  我也蒙蒙的，代码让我注释掉，参数改改，苹果WIFI 连接上了。苹果不知道是不是系统版本问题(11的系统)，数据线一直连接不上

**Comment by lebang08** [comment]
@fuliteng 同样，在摸索。可不可以将你修改的代码放到你github上，参考学习一下

**Comment by fuliteng** [comment]
@lebang08 我也没改什么，QQ邮箱，苹果WIFI连接 ConnectManager.java(类中) initConnectType（方法），把类别写死WIFI的 getIphoneConnectType（方法）把类别写死 WIFI的
