### ISSUE TITLE
读取配置文件失败

### ISSUE THREAD

**Issue by BrandonHe** [ApolloAuto/apollo-DuerOS#5]
尝试在安卓手机上运行车机端Baidu CarLife（Android 6.0 和 Android7.0），显示如下错误：
![screenshot_20180118-103500](https://user-images.githubusercontent.com/13449160/35079278-5bc7d7d8-fc41-11e7-85a6-f5aded158ec3.png)

请问这里需要什么配置文件吗？
根据指导文档.bdsc文件只需要在Android5.0以下的系统上才需要。

谢谢，

**Comment by fuliteng** [comment]
要的吧 ，https://github.com/ApolloAuto/apollo-DuerOS/tree/master/CarLife-Android-Vehicle
Copy bdcf from the catalog of assets to the catalog of /data/local/tmp of the vehicle

**Comment by fuliteng** [comment]
不是说了 assets  目录下有吗

**Comment by fuliteng** [comment]
@BrandonHe  不是说了 assets 目录下有吗,其他文件，你去下手机版或WinCE版本的解压后找吧

**Comment by BrandonHe** [comment]
@fuliteng 谢谢  找到了！
