### ISSUE TITLE
咨询关于CarLife Head Unit 端硬件及软件的配置信息

### ISSUE THREAD

**Issue by hongkedavid** [ApolloAuto/apollo-DuerOS#6]
CarLife开发者，你好！请问能不能提供一些CarLife Head Unit 端硬件及软件的配置信息或者相关的文档？比如我想知道CarLife Head Unit是通过什么端口连到车上。它是独立于车的一个中控系统（车只是提供电源的支持），还是会跟车的一些控件（比如CAN bus）进行通讯交互的？还有Head Unit跑的是什么操作系统？

**Comment by fuliteng** [comment]
CarLife Head Unit 这是什么，CarLife 这个Github上的项目是运行在普通Android系统上，功能是手机版的功能只是做了个投屏操作，跟车上没关系，但是用到音频和蓝牙等设备的

**Comment by hongkedavid** [comment]
@fuliteng 谢谢你的回答！
我是在[README](https://github.com/ApolloAuto/apollo-DuerOS/blob/master/ReadMe.md)里看到了Head Unit这个东西，但不确定它是一个专门为DuerOS定制的head unit, 还是现在一般车上的head unit就可以兼容CarLife？

> CarLife is a Smartphone-Integration solution, with which drivers can share the mobile applications suitable for safe driving conditions on MD (Mobile Device) to HU (Head Unit) through the multi-screen sharing and interaction technology, and use the Touch Screen, Hard Keys, Knob Control and Microphone to control CarLife. 

所以CarLife是提供投射手机屏幕到head unit上并控制车上音频蓝牙等设备的一个Android app？功能类似于现在市面上Honda的CarPlay系统？如果是这样的话head unit端应该也要跑CarLife的服务吧，请问有没有这方面相关的项目或文档？

另外，据你所知CarLife这套系统是为Apollo无人车量身订造的吗？

**Comment by AllenMeex** [comment]
@fuliteng 有点没明白，Carlife这个这个项目运行在Android系统的车机端，既然功能都包含了手机版的功能了，为何还要加个投屏的功能

**Comment by feixhan** [comment]
@fuliteng head unit就是汽车上的中控，一般车上的head unit都可以兼容CarLife。这个就是在汽车上跑的app。
功能类似Apple CarLife，MirrorLink,Android Auto。

**Comment by PeiLinCN** [comment]
@Felix,
                I think there is one typo in your reply, APPLE’s solution is named *CarPlay* and Baidu’s *CarLife*.

Thanks,
-Lin

**Comment by feixhan** [comment]
@PeiLinCN Yes you are right, i have fixed it.thank you.

**Comment by luoxubin** [comment]
您好，如果您的车机需要搭载CarLife，请在CarLife 官网（carlife.baidu.com）先申请渠道号，获得相关的项目材料，github上的这个项目是针对具体车机端的开发示例和讨论。
